packages:
  - apps/*
  - packages/*

ignoredBuiltDependencies:
  - '@parcel/watcher'

onlyBuiltDependencies:
  - '@nestjs/core'
  - '@swc/core'
  - '@tailwindcss/oxide'
  - mongodb-memory-server
  - sharp
  - unrs-resolver
